import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Early theme initialization to avoid flash */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
  try {
    const ls = typeof localStorage !== 'undefined' ? localStorage.getItem('theme') : null;
    const prefersDark = typeof window !== 'undefined' && window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
    const theme = ls === 'light' || ls === 'dark' ? ls : (prefersDark ? 'dark' : 'light');
    const el = document.documentElement;
    el.setAttribute('data-theme', theme);
  } catch {}
})();`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
